services:
  db:
    image: postgres:latest
    restart: always
    container_name: morning-compass-db
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: morning-compass
    ports:
      - "3400:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  frontend:
    build: .
    container_name: morning-compass-project
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./target:/app/target
    command: ["sh", "-c", "CARGO_TARGET_DIR=/app/src-tauri/target xvfb-run -s '-screen 0 1024x768x24' cargo tauri dev"]

volumes:
  postgres:
    driver: local