services:
  db:
    image: postgres:latest
    restart: always
    container_name: morning-compass-db
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: morning-compass
    ports:
      - "3400:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build: .
    container_name: morning-compass-project
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["sh", "-c", "cargo tauri dev"]
    

volumes:
  postgres:
    driver: local