services:
  db:
    image: postgres:latest
    restart: always
    container_name: morning-compass-db
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: morning-compass
    ports:
      - "3400:3400"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    image: node:latest
    volumes:
      - ./morning-compass-nextjs:/home/node/app
    working_dir: "/app"
    command: ["yarn", "dev"]
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  postgres-data: